CREATE TABLE t (
    COL_01 INT NOT NULL,
    COL_02 VARCHAR(50) NOT NULL,
    COL_03 VARCHAR(200),
    COL_04 VARCHAR(50) NOT NULL,
    COL_05 VARCHAR(50),
    COL_06 INT,
    COL_07 VARCHAR(1) NOT NULL,
    COL_08 DATE NOT NULL,
    COL_88 DATE NOT NULL,
    COL_09 TIMESTAMP NOT NULL,
    COL_10 TIMESTAMP NOT NULL
);